### ISSUE TITLE
It possible to configure the logger which allows CRLF injection.

### ISSUE THREAD

**Issue by nozmore** [darrenpmeyer/logging-formatter-anticrlf#1]
If I were to set `formatter.replacements["\n"] = "\n"` then this logger will allow CRLF injection. 

The `format` method should have logic to detect this and use some local variables in the method as default values. So if the above happens it will replace the value with \\n or something similar.

**Comment by darrenpmeyer** [comment]
I accept that this is a way that's to easy for developers to accidentally create an unsafe situation. I'm not sure the exact fix proposed is the right way to solve it, but I will investigate

**Comment by darrenpmeyer** [comment]
Solution basics:

- Added `SubstitutionMap` class and force `replacements` field to use it.
- Added `UnsafeSubstitutionError` 

- Trying to adjust the `replacements` field in unsafe ways raises an exception
- if `replacements` is not a `SubstitutionMap` at time of logging, a default (safe) replacement is made and a warning issued (exceptions in formatters are caught by `logging` handlers, so this was the only reasonable option)
- Trying to delete the CR or LF substitution merely resets that substitution to the safe default
