### ISSUE TITLE
Infinite recursion with initialization

### ISSUE THREAD

**Issue by MaddenJohn** [darrenpmeyer/logging-formatter-anticrlf#5]
There is an infinite recursion issue, which can happen when initializing the superclass. See this thread for an example. https://stackoverflow.com/questions/4235078/how-to-avoid-infinite-recursion-with-super. An example solution which is not compatible with lower versions is seen here: https://github.com/darrenpmeyer/logging-formatter-anticrlf/pull/4

**Comment by darrenpmeyer** [comment]
I agree this _can_ happen, however it would be on the next inheritor to handle it correctly
